### ISSUE TITLE
Decorators break Python 2

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#150]
I get an error with the most recent code using Python 2:

    Traceback (most recent call last):
      File "xnmt/xnmt_run_experiments.py", line 10, in <module>
        import xnmt_preproc, xnmt_train, xnmt_decode, xnmt_evaluate
      File "/Users/neubig/work/xnmt/xnmt/xnmt_train.py", line 13, in <module>
        from encoder import *
      File "/Users/neubig/work/xnmt/xnmt/encoder.py", line 8, in <module>
        from decorators import recursive
      File "/Users/neubig/work/xnmt/xnmt/decorators.py", line 29
        def rec_f(obj, *args, **kwargs, context=None):
                                          ^
     SyntaxError: invalid syntax

Any ideas @philip30 ?

**Comment by philip30** [comment]
I see, this is not possible actually in python 2:

https://stackoverflow.com/questions/5940180/python-default-keyword-arguments-after-variable-length-positional-arguments

I will make a bit uglier code to make this possible.

**Comment by philip30** [comment]
7ed26ed67bbf7cbc968263d67a8467e9d60181bf

**Comment by philip30** [comment]
Fixed in: 7ed26ed67bbf7cbc968263d67a8467e9d60181bf
