### ISSUE TITLE
Checking string instance different between Python2/Python3 in tokenization

### ISSUE THREAD

**Issue by neilzxu** [neulab/xnmt#244]
Reproduce
`python3 ~/src/xnmt/xnmt/xnmt_run_experiments.py examples/preproc.yaml`
with the appropriate paths substituted in for tokenizers.

Output:
```
Traceback (most recent call last):
  File "/home/ziyux/src/xnmt/xnmt/xnmt_run_experiments.py", line 154, in <module>
    sys.exit(main())
  File "/home/ziyux/src/xnmt/xnmt/xnmt_run_experiments.py", line 84, in main
    xnmt.xnmt_preproc.xnmt_preproc(**preproc_args)
  File "/home/ziyux/src/xnmt/xnmt/xnmt_preproc.py", line 47, in xnmt_preproc
    in_stream = tokenizer.tokenize_stream(in_stream)
  File "/home/ziyux/src/xnmt/xnmt/preproc.py", line 95, in tokenize_stream
    tokenized_string = self._tokenize(stream.read())
  File "/home/ziyux/src/xnmt/xnmt/preproc.py", line 160, in _tokenize
    if isinstance(string, unicode):
NameError: name 'unicode' is not defined
```

**Comment by neubig** [comment]
Should be fixed by #248
