### ISSUE TITLE
Cant' Run test

### ISSUE THREAD

**Issue by philip30** [neulab/xnmt#282]
I got this error when trying python3 -m unittest discover

```
EEEEE..EEEEEEEEEEEEExEEEEE............E
======================================================================
ERROR: test.test_batcher (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_batcher
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/philip-a/tools/xnmt/test/test_batcher.py", line 3, in <module>
    import xnmt.batcher
  File "/Users/philip-a/tools/xnmt/xnmt/batcher.py", line 6, in <module>
    import dynet as dy
  File "/usr/local/lib/python3.6/site-packages/dyNET-0.0.0-py3.6-macosx-10.12-x86_64.egg/dynet.py", line 32, in <module>
    _params.from_config(_CONF)
  File "_dynet.pyx", line 70, in _dynet.DynetParams.from_config (/Users/philip-a/tools/dynet/build/python/_dynet.cpp:6245)
  File "_dynet.pyx", line 79, in _dynet.DynetParams.from_config (/Users/philip-a/tools/dynet/build/python/_dynet.cpp:6077)
KeyError: 'profiling'
```
Maybe @neubig  knows the problem?

**Comment by philip30** [comment]
I have tried rebuilding dynet

**Comment by philip30** [comment]
Following up! I can't run the test using 

```
python3 -m unittest test.test_run
```

**Comment by philip30** [comment]
Now getting this error from the latest master branch:

```
[dynet] initializing CUDA
[dynet] Request for 1 specific GPU ...
[dynet] Device(s) selected: 0GPU memory allocation failed n=0
terminate called after throwing an instance of 'dynet::out_of_memory'
  what():  GPU memory allocation failed
[2]    30059 abort      python3 -m unittest discover
```

**Comment by msperber** [comment]
Hey Philip, I'm guessing this is a problem with the (DyNet) installation? Things work perfectly fine for me, even if I install a virtualenv from scratch.

**Comment by philip30** [comment]
I think I solved this. Thank you!
