### ISSUE TITLE
Debug mode doesn't work with CUDA

### ISSUE THREAD

**Issue by mbollmann** [neulab/xnmt#287]
When running an experiment with both `--settings=settings.debug` and `--dynet-gpu`, the code crashes for me (e.g., on the `01_standard.yaml` example).

Maybe this seems trivial (as in, just don't debug on GPU), but it took me a while to figure out that this was the simple cause, so maybe document this or catch this somewhere?

Full traceback:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/marcel/xnmt/xnmt/xnmt_run_experiments.py", line 110, in <module>
    sys.exit(main())
  File "/home/ubuntu/marcel/xnmt/xnmt/xnmt_run_experiments.py", line 89, in main
    eval_scores = experiment(save_fct = lambda: yaml_serializer.save_to_file(model_file, experiment,
  File "/home/ubuntu/marcel/xnmt/xnmt/experiment.py", line 35, in __call__
    self.train.run_training(save_fct = save_fct)
  File "/home/ubuntu/marcel/xnmt/xnmt/training_regimen.py", line 103, in run_training
    loss = self.training_step(src, trg)
  File "/home/ubuntu/marcel/xnmt/xnmt/training_task.py", line 244, in training_step
    standard_loss = self.model.calc_loss(src, trg, self.loss_calculator)
  File "/home/ubuntu/marcel/xnmt/xnmt/translator.py", line 124, in calc_loss
    self.start_sent(src)
  File "/home/ubuntu/marcel/xnmt/xnmt/events.py", line 68, in wrapper
    ret = bound_handler(*args, **kwargs)
  File "/home/ubuntu/marcel/xnmt/xnmt/events.py", line 110, in wrapper
    return f(obj, *args, **kwargs), f.__name__
  File "/home/ubuntu/marcel/xnmt/xnmt/lstm.py", line 45, in on_start_sent
    self.Wx = dy.parameter(self.p_Wx)
  File "_dynet.pyx", line 2069, in _dynet.parameter
  File "_dynet.pyx", line 716, in _dynet.Parameters.expr
  File "_dynet.pyx", line 731, in _dynet.Parameters.expr
RuntimeError: is_valid() not implemented for CUDA yet. You can use CPU implementation with to_device operation instead.
```
DyNet was installed from git:
```bash
$ python3 -c "import dynet; print(dynet.__gitversion__)"
2.0.3-11-g18ed6b7
```

**Comment by msperber** [comment]
Thanks for the hint! I fixed it by disabling validity checks when running on GPU (214020f)
