### ISSUE TITLE
Multi-task learning breaks with shared decoders

### ISSUE THREAD

**Issue by mbollmann** [neulab/xnmt#309]
Modifying the supplied `10_multi_task.yaml` example to share the decoder results in the following error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bollmann/repositories/xnmt-fork/xnmt/xnmt_run_experiments.py", line 118, in <module>
    sys.exit(main())
  File "/home/bollmann/repositories/xnmt-fork/xnmt/xnmt_run_experiments.py", line 97, in main
    eval_scores = experiment(save_fct = lambda: yaml_serializer.save_to_file(model_file, experiment,
  File "/home/bollmann/repositories/xnmt-fork/xnmt/experiment.py", line 63, in __call__
    self.train.run_training(save_fct = save_fct)
  File "/home/bollmann/repositories/xnmt-fork/xnmt/training_regimen.py", line 188, in run_training
    task_losses.append(task.training_step(src, trg))
  File "/home/bollmann/repositories/xnmt-fork/xnmt/training_task.py", line 254, in training_step
    standard_loss = self.model.calc_loss(src, trg, self.loss_calculator)
  File "/home/bollmann/repositories/xnmt-fork/xnmt/translator.py", line 127, in calc_loss
    dec_state = self.decoder.initial_state(self.encoder.get_final_states(), self.trg_embedder.embed(ss))
  File "/home/bollmann/repositories/xnmt-fork/xnmt/decoder.py", line 176, in initial_state
    rnn_state = rnn_state.add_input(dy.concatenate([ss_expr, zeros]))
  File "_dynet.pyx", line 5556, in _dynet.RNNState.add_input
  File "_dynet.pyx", line 5566, in _dynet.RNNState.add_input
  File "_dynet.pyx", line 4638, in _dynet._RNNBuilder.add_input_to_prev
ValueError: VanillaLSTMGates: dropout_mask_x expected to have batch size 1 or 3, was 4
```

This error appears whether or not dropout is actually used, and apparently still occurs even if I set the batch sizes for each task to be identical. (The numbers in the error message do change, though.)

**Comment by mbollmann** [comment]
I can no longer replicate the issue with the newest commits: it works fine to share `decoder.rnn_layer`, `decoder.mlp_layer`, or both at the same time.

Sharing the full `decoder` however fails with
```
xnmt.serialize.tree_tools.PathError: Ref(name=decoder) has no child named rnn_layer
```

**Comment by msperber** [comment]
Could you attach a breaking config file? I'll take a look at it.

**Comment by mbollmann** [comment]
Here you are:
[12b_multi_task_broken.yaml.gz](https://github.com/neulab/xnmt/files/1880303/12b_multi_task_broken.yaml.gz)
