### ISSUE TITLE
Impossible to run preprocessing without training

### ISSUE THREAD

**Issue by pmichel31415** [neulab/xnmt#389]
I want to evaluate my model on new test sets for which I need to run preprocessing (tokenization, etc...).

I'm using a similar config file as the one in https://github.com/neulab/xnmt/blob/master/examples/08_load_eval_beam.yaml (the second experiment), just replacing the value of preproc with whatever I need.

However, it seems that these preprocessing tasks are never executed.

**Comment by msperber** [comment]
I've been running preprocessing without training and never had a problem so far. I could take a look if you could provide a reproducible example?

**Comment by pmichel31415** [comment]
OK here is my evaluation experiment file:

```yaml
europarl-en-fr-eval: !LoadSerialized
  filename: 'recipes/models/europarl-en-fr.mod'
  overwrite: # list of [path, value] pairs. Value can be scalar or an arbitrary object
  - path: preproc
    val:
      overwrite: True
      tasks:
      - !PreprocTokenize
        in_files:
        - '{EXP_DIR}/../fr/tst2015.en'
        out_files:
        - '{EXP_DIR}/../fr/tst2015.tok.en'
        specs:
        - filenum: all
          tokenizers:
          - !SentencepieceTokenizer
            path: ''
            train_files: ''
            vocab_size: 16000
            model_prefix: '{EXP_DIR}/en-fr.en.bpe.16k'
      - !PreprocTokenize
        in_files:
        - '{EXP_DIR}/../fr/tst2015.fr'
        out_files:
        - '{EXP_DIR}/../fr/tst2015.tok.fr'
        specs:
        - filenum: all
          tokenizers:
          - !SentencepieceTokenizer
            path: ''
            train_files: ''
            vocab_size: 16000
            model_type: bpe
            model_prefix: '{EXP_DIR}/en-fr.fr.bpe.16k'
  - path: train # skip the training loop
    val: null
  - path: model.inference.search_strategy.beam_size # try some new beam settings
    val: 10
  - path: evaluate
    val: # (re-)define test data and other evaluation settings
    - !AccuracyEvalTask
      eval_metrics: bleu,gleu
      src_file: '{EXP_DIR}/../fr/tst2015.tok.en'
      ref_file: '{EXP_DIR}/../fr/tst2015.fr'
      hyp_file: 'recipes/hyp/{EXP}.tst2015.hyp.fr'
    - !AccuracyEvalTask
      eval_metrics: bleu,gleu
      src_file: '{EXP_DIR}/../fr/newstest2014.tok.en'
      ref_file: '{EXP_DIR}/../fr/newstest2014.fr'
      hyp_file: 'recipes/hyp/{EXP}.newstest2014.hyp.fr'
    - !AccuracyEvalTask
      eval_metrics: bleu,gleu
      src_file: '{EXP_DIR}/../fr/test.tok.en'
      ref_file: '{EXP_DIR}/../fr/test.fr'
      hyp_file: '{EXP_DIR}/hyp/{EXP}.test.fr'
```

And here is the output I get

```
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: TITAN X (Pascal)
[dynet]   Memory Clock Rate (KHz): 5005000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 480.48
[dynet]   Memory Free (GB): 12.6049/12.7885
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 1349792462
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
running XNMT revision feb3951 on compute-0-15.local on 2018-05-10 15:53:14
=> Running europarl-en-fr-eval
> populated DyNet weights of all components from given data files
> Performing final evaluation
Traceback (most recent call last):
  File "/home/pmichel1/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pmichel1/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/projects/tir1/users/pmichel1/xnmt/xnmt/xnmt_run_experiments.py", line 121, in <module>
    sys.exit(main())
  File "/projects/tir1/users/pmichel1/xnmt/xnmt/xnmt_run_experiments.py", line 104, in main
    eval_scores = experiment(save_fct = lambda: save_to_file(model_file, experiment))
  File "/projects/tir1/users/pmichel1/xnmt/xnmt/experiment.py", line 64, in __call__
    eval_score, _ = evaluator.eval()
  File "/projects/tir1/users/pmichel1/xnmt/xnmt/eval_task.py", line 121, in eval
    candidate_id_file = self.candidate_id_file)
  File "/projects/tir1/users/pmichel1/xnmt/xnmt/inference.py", line 68, in __call__
    src_corpus = list(generator.src_reader.read_sents(args["src_file"]))
  File "/projects/tir1/users/pmichel1/xnmt/xnmt/input_reader.py", line 81, in iterate_filtered
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'recipes/../fr/tst2015.tok.en'
```

there is no error message when the preprocessed files already exist. Let me know if you need more info.

**Comment by msperber** [comment]
It's possible that you need to change this:

```
  - path: preproc
    val:
```

into

```
  - path: preproc
    val: !PreprocRunner
```

Otherwise ```preproc``` will be a dictionary which will not carry out anything when initialized. We could probably use some better type checking to catch cases like this.

**Comment by pmichel31415** [comment]
Thank you! Looks like this was it 👍
