### ISSUE TITLE
Question regarding circular imports

### ISSUE THREAD

**Issue by neubig** [neulab/xnmt#489]
This is question for @msperber:

With the new convention of using `from xnmt import aaa, bbb`, I thought we could avoid problems from circular imports. However, I seem to be encountering a problem regarding circular imports in my `refactor-loss` branch: https://github.com/neulab/xnmt/pull/486

Here is the error:

    (python3) tanuki:xnmt neubig$ xnmt test/config/reinforce.yaml 
    [dynet] random seed: 3638489646
    [dynet] allocating memory: 512MB
    [dynet] memory allocation done.
    Traceback (most recent call last):
      File "/Users/neubig/anaconda3/envs/python3/bin/xnmt", line 11, in <module>
        load_entry_point('xnmt', 'console_scripts', 'xnmt')()
      File "/Users/neubig/anaconda3/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/Users/neubig/anaconda3/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
        return ep.load()
      File "/Users/neubig/anaconda3/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
        return self.resolve()
      File "/Users/neubig/anaconda3/envs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/Users/neubig/work/xnmt/xnmt/__init__.py", line 26, in <module>
        import xnmt.classifiers
      File "/Users/neubig/work/xnmt/xnmt/classifiers.py", line 3, in <module>
        from xnmt import batchers, embedders, inferences, input_readers, losses, recurrent_transducers, model_base, output, scorers, transducers, transforms
      File "/Users/neubig/work/xnmt/xnmt/inferences.py", line 9, in <module>
        from xnmt import events, losses, loss_calculators, model_base, output, reports, search_strategies, utils
      File "/Users/neubig/work/xnmt/xnmt/search_strategies.py", line 8, in <module>
        from xnmt import batchers, logger, translators
      File "/Users/neubig/work/xnmt/xnmt/translators.py", line 76, in <module>
        class DefaultTranslator(AutoRegressiveTranslator, Serializable, Reportable, model_base.EventTrigger):
      File "/Users/neubig/work/xnmt/xnmt/translators.py", line 104, in DefaultTranslator
        inference: inferences.AutoRegressiveInference=bare(inferences.AutoRegressiveInference),

`AutoRegressiveInference` is included in `inferences.py`, so I thought that this should work, but it seems like it's not. Do you have any ideas?

**Comment by msperber** [comment]
Hm, first the commit was only meant to prepare refactoring the imports by renaming things so that we can use ```from xnmt import x``` without worrying about name clashes too much. Most of the imports actually haven't changed yet. The line ```class DefaultTranslator(AutoRegressiveTranslator, Serializable, Reportable, model_base.EventTrigger):``` suggests that several classes are not imported via this way. ```Serializable``` doesn't have a lot of dependencies itself so it shouldn't be a problem, but the other two might better be imported the new style.

If that doesn't solve the problem: while the ```from xnmt import module``` style has worked for me in most cases and is recommended in the Python docs, but I think it won't solve all circular import problems. So far the case where it hasn't worked for me were always possible to solve by writing type annotations as strings.

If neither of these two work, I think the only way is improving the module structure..

**Comment by neubig** [comment]
Thanks! I re-wrote the type annotations as strings and that seems to have solved the problem. We probably will need to reconsider the module structure at some point though if we're going to be consistent in type annotation.

**Comment by msperber** [comment]
Yeah.. another thing that could help is switching to Python 3.7 which support postponed evaluation of type annotations: https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep563

**Comment by neubig** [comment]
Ooh, nice. Might be good to wait for a little bit before requiring Python 3.7 though, as it's really new at the moment.
