### ISSUE TITLE
Problem while using SAAMSeqTransducer

### ISSUE THREAD

**Issue by tenghaha** [neulab/xnmt#571]
hi @neubig ，
I try to run self-attentional-am experiment following this article
https://arxiv.org/abs/1803.09519
And I used class `SAAMSeqTransducer` defined in xnmt/specialized_encoders/self_attentional_am.py . When I started the experiment, the following error is raised:

```
$ CUDA_VISIBLE_DEVICES=5 xnmt --dynet-gpu --settings=debug exp/saam/tab2_row2.yaml
[dynet] initializing CUDA
[dynet] CUDA driver/runtime versions are 8.0/9.2
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: Tesla P40
[dynet]   Memory Clock Rate (KHz): 3615000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 347.04
[dynet]   Memory Free (GB): 6.22336/24.0324
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 1144512328
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
initialized : GlorotInitializer@140179513821504({})
initialized : ZeroInitializer@140179513821728({})
initialized : GlorotInitializer@140179513822904({})
initialized : ZeroInitializer@140179513880648({})
initialized : GlorotInitializer@140179513881096({})
initialized : ZeroInitializer@140179513880872({})
initialized : GlorotInitializer@140179513951680({})
initialized : ZeroInitializer@140179513952128({})
initialized : GlorotInitializer@140179513952352({})
initialized : GlorotInitializer@140179514021480({})
initialized : ZeroInitializer@140179514021928({})
initialized : GlorotInitializer@140179513561160({})
initialized : ZeroInitializer@140179513561608({})
initialized : GlorotInitializer@140179513562504({})
initialized : ZeroInitializer@140179513562952({})
initialized : GlorotInitializer@140179513562728({})
initialized : ZeroInitializer@140179513563176({})
initialized : GlorotInitializer@140179513610312({})
initialized : ZeroInitializer@140179513610760({})
initialized : GlorotInitializer@140179513639432({})
initialized : ZeroInitializer@140179513639880({})
initialized : GlorotInitializer@140179513640664({})
initialized : GlorotInitializer@140179513641504({})
initialized : GlorotInitializer@140181247629240({})
initialized : GlorotInitializer@140181172780448({})
initialized : ZeroInitializer@140181172780784({})
initialized : GlorotInitializer@140180795622120({})
initialized : ZeroInitializer@140180795622568({})
initialized : GlorotInitializer@140180795623016({})
initialized : ZeroInitializer@140180795623352({})
WARNING: disabling CHECK_VALIDITY because it is not supported on GPU currently
running XNMT revision a87e7b9 on ubuntu on 2019-05-22 18:26:01
=> Running exp029a.1
initialized exp_global.param_init: GlorotInitializer@140180795384048({})
initialized exp_global.bias_init: ZeroInitializer@140180795386456({})
initialized exp_global: ExpGlobal@140180795384608({'model_file': 'exp/saam/models/exp029a.1.mod', 'log_file': 'exp/saam/logs/exp029a.1.log', 'dropout': 0.2, 'weight_noise': 0.0, 'default_layer_dim': 512, 'param_init': GlorotInitializer@140180795432856, 'bias_init': ZeroInitializer@140180795432072, 'truncate_dec_batches': False, 'loss_comb_method': 'sum', 'commandline_args': Namespace(dynet_autobatch=None, dynet_devices=None, dynet_gpu=True, dynet_gpu_ids=None, dynet_gpus=None, dynet_mem=None, dynet_profiling=None, dynet_seed=None, dynet_viz=False, dynet_weight_decay=None, experiment_name=[], experiments_file='exp/saam/tab2_row2.yaml', generate_doc=False, settings='debug'), 'placeholders': {'DATA_DIR': '/data/xiaoyun.xu/tyt/xnmt-0.1.0/data/tedlium'}})
initialized model.src_reader: NpzReader@140180795450312({'transpose': True, 'feat_from': 0, 'feat_to': 40})
initialized model.trg_reader.vocab: Vocab@140180795450760({'vocab_file': '/data/xiaoyun.xu/tyt/xnmt-0.1.0/data/tedlium/train/src.char.vocab.manual'})
initialized model.trg_reader: PlainTextReader@140180795452720({'vocab': Vocab@140180795292752})
initialized model.src_embedder: NoopEmbedder@140180795385280({'emb_dim': 40})
for model.encoder.modules.0.param_init: reusing previously initialized GlorotInitializer@140180795432856
for model.encoder.modules.0.bias_init: reusing previously initialized ZeroInitializer@140180795432072
Traceback (most recent call last):
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1215, in init_component
    initialized_obj = obj.__class__(**init_params)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 84, in wrapper
    f(obj, **serialize_params)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/events.py", line 63, in wrapper
    f(obj, *args, **kwargs)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/specialized_encoders/self_attentional_am.py", line 527, in __init__
    lambda: self.make_modules(layers=layers,
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 185, in add_serializable_component
    initialized = create_fct()
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/specialized_encoders/self_attentional_am.py", line 545, in <lambda>
    bias_init=bias_init))
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/specialized_encoders/self_attentional_am.py", line 575, in make_modules
    desc=f"layer_{layer_i}"))
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 84, in wrapper
    f(obj, **serialize_params)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/specialized_encoders/self_attentional_am.py", line 422, in __init__
    lambda: SAAMPositionwiseFeedForward(hidden_dim, ff_hidden_dim,
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 185, in add_serializable_component
    initialized = create_fct()
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/specialized_encoders/self_attentional_am.py", line 424, in <lambda>
    param_init=param_init))
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 84, in wrapper
    f(obj, **serialize_params)
TypeError: __init__() got an unexpected keyword argument 'param_init'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/bin/xnmt", line 11, in <module>
    load_entry_point('xnmt==0.0.1', 'console_scripts', 'xnmt')()
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/xnmt_run_experiments.py", line 98, in main
    experiment = initialize_if_needed(uninitialized_exp_args)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1297, in initialize_if_needed
    return _YamlDeserializer().initialize_if_needed(root)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1038, in initialize_if_needed
    else: return self.initialize_object(deserialized_yaml_wrapper=obj)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1081, in initialize_object
    initialized = self.init_components_bottom_up(self.deserialized_yaml)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1180, in init_components_bottom_up
    initialized_component = self.init_component(path)
  File "/data/xiaoyun.xu/tyt/xnmt-0.1.0/venv/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1218, in init_component
    raise ComponentInitError(f"An error occurred when calling {type(obj).__name__}.__init__()\n"
xnmt.persistence.ComponentInitError: An error occurred when calling SAAMSeqTransducer.__init__()
 The following arguments were passed: OrderedDict([('input_dim', 40), ('layers', 2), ('hidden_dim', 512), ('ff_hidden_dim', 512), ('dropout', 0.2), ('downsample_factor', 2), ('pos_encoding_type', 'trigonometric'), ('pos_encoding_combine', 'concat'), ('pos_encoding_size', 40), ('max_len', 1500), ('param_init', GlorotInitializer@140180795432856), ('bias_init', ZeroInitializer@140180795432072)])
 The following arguments were expected: odict_keys(['input_dim', 'layers', 'hidden_dim', 'head_count', 'ff_hidden_dim', 'dropout', 'downsample_factor', 'diagonal_mask_width', 'ignore_masks', 'plot_attention', 'nonlinearity', 'pos_encoding_type', 'pos_encoding_combine', 'pos_encoding_size', 'max_len', 'diag_gauss_mask', 'square_mask_std', 'cross_pos_encoding_type', 'ff_lstm', 'kq_pos_encoding_type', 'kq_pos_encoding_size', 'param_init', 'bias_init', 'positional_embedder', 'modules'])
 Current path: model.encoder.modules.0
 Error message: __init__() got an unexpected keyword argument 'param_init'
```
But the err info shows that the argument  'param_init' exist in class `SAAMSeqTransducer` , is this a bug?
My python version is 3.6.4, if you need more information about it, please tell me and i'll fix it.

**Comment by philip30** [comment]
Hi, can you copy paste your yaml file here? I can try to take a look

**Comment by tenghaha** [comment]
@philip30 I'm using the defalut configuration file provided by the article
http://www.msperber.com/research/self-att/index.html
but I can't changed tag `TransformerSeqTransducer` to `SAAMSeqTransducer`, and `ContVecReader` to `NpzReader`


# purely self-att model, using concatenated 'trigonometric' positional encodings
exp029a.1: !Experiment
  exp_global: !ExpGlobal
    dropout: 0.2
    default_layer_dim: 512
    placeholders:
      DATA_DIR: (removed)
  model: !DefaultTranslator
    src_embedder: !NoopEmbedder
      emb_dim: 40
    encoder: !ModularSeqTransducer
      modules:
      - !SAAMSeqTransducer
        layers: 2
        input_dim: 40
        hidden_dim: 512
        downsample_factor: 2
        ff_hidden_dim: 512
        pos_encoding_type: trigonometric
        pos_encoding_combine: concat
        pos_encoding_size: 40
        max_len: 1500
      - !SAAMSeqTransducer
        layers: 1
        input_dim: 512
        hidden_dim: 512
        downsample_factor: 1
        ff_hidden_dim: 512
    attender: !MlpAttender
      hidden_dim: 128
    trg_embedder: !SimpleWordEmbedder
      emb_dim: 64
      word_dropout: 0.1
      fix_norm: 1
    decoder: !MlpSoftmaxDecoder
      layers: 1
      lstm_dim: 512
      input_feeding: True
      bridge: !NoBridge {}
    src_reader: !NpzReader
      transpose: true
      feat_from: 0
      feat_to: 40
    trg_reader: !PlainTextReader
      vocab: !Vocab
        vocab_file: '{DATA_DIR}/train/src.char.vocab.manual'
  train: !SimpleTrainingRegimen
    src_file: '{DATA_DIR}/train/src.contvec.npz'
    trg_file: '{DATA_DIR}/train/src.char'
    max_src_len: &max_src_len 1500
    max_trg_len: 350
    run_for_epochs: 500
    batcher: !WordSrcBatcher
      avg_batch_size: 18
      pad_src_to_multiple: 4
      src_pad_token: ~
    trainer: !AdamTrainer
      alpha: 0.0003
    lr_decay: 0.5
    lr_decay_times: 3
    patience: 5
    initial_patience: 10
    dev_every: 0
    restart_trainer: True
    dev_tasks:
      - !AccuracyEvalTask
        eval_metrics: wer,cer
        src_file: &dev_src '{DATA_DIR}/dev/src.contvec.npz'
        ref_file: '{DATA_DIR}/dev/src.txt'
        hyp_file: '{EXP_DIR}/models/{EXP}.dev_hyp'
        inference: !SimpleInference
          post_process: join-char
          search_strategy: !BeamSearch
            beam_size: 20
            max_len: 500
            len_norm: !PolynomialNormalization
              apply_during_search: true
              m: 1.5
      - !LossEvalTask
        src_file: *dev_src
        ref_file: '{DATA_DIR}/dev/src.char'
  evaluate:
    - !AccuracyEvalTask
      eval_metrics: wer,cer
      src_file: &test_src '{DATA_DIR}/test/src.contvec.npz'
      ref_file: '{DATA_DIR}/test/src.txt'
      hyp_file: '{EXP_DIR}/models/{EXP}.test_hyp'
      inference: !SimpleInference
        post_process: join-char
        search_strategy: !BeamSearch
          beam_size: 20
          max_len: 500
          len_norm: !PolynomialNormalization
            apply_during_search: true
            m: 1.5
    - !LossEvalTask
      src_file: *test_src
      ref_file: '{DATA_DIR}/test/src.char'

**Comment by philip30** [comment]
Hmm this is very strange. Which revision of the xnmt are you using? I will try to reproduce the issue

**Comment by tenghaha** [comment]
XNMT: 0.1.0 release
Python: 3.6.4 (I tried 3.6.8, same error - - )
OS: Ubuntu 16.04

**Comment by tenghaha** [comment]
@philip30 I think I found the key.
When I set argument 'ff_lstm' to 'true', it works normally.
I'm trying to find out the reason.

**Comment by philip30** [comment]
Thanks! I am closing this issue.
