### ISSUE TITLE
standard example seems broken

### ISSUE THREAD

**Issue by roeeaharoni** [neulab/xnmt#87]
Hi, 

First of all, as a dynet/nmt fan, this project is very exciting! 

To the issue: I tried running the standard example from the documentation using:

`python xnmt/xnmt_run_experiments.py examples/standard.yaml`

And got the following output:
```
[dynet] random seed: 2045434078
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "xnmt/xnmt_run_experiments.py", line 108, in <module>
    config = config_parser.args_from_config_file(args.experiments_file)
  File "/home/nlp/aharonr6/git/xnmt/xnmt/options.py", line 105, in args_from_config_file
    {name: self.check_and_convert(task_name, name, value) for name, value in exp_task_values.items()})
  File "/home/nlp/aharonr6/git/xnmt/xnmt/options.py", line 105, in <dictcomp>
    {name: self.check_and_convert(task_name, name, value) for name, value in exp_task_values.items()})
  File "/home/nlp/aharonr6/git/xnmt/xnmt/options.py", line 42, in check_and_convert
    raise RuntimeError("Unknown option {} for task {}".format(option_name, task_name))
RuntimeError: Unknown option encoder_layers for task train
```
Is the example broken or is it me doing something wrong?
Thanks!

**Comment by neubig** [comment]
Thanks for pointing this out! This was broken by: https://github.com/neulab/xnmt/pull/83 and I just fixed it now here: https://github.com/neulab/xnmt/commit/6097dc06a58f88fd6c204e2bef0629f856503e17
